theme = "gruvbox"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-h = ":bp"
C-l = ":bn"
# C-x = ["game-of-life"]
C-s = "@*%s<ret>"
